# Generated by Django 5.1.2 on 2025-01-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikkari_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=5, verbose_name='部署コード')),
                ('product_name', models.CharField(max_length=10, verbose_name='部署名')),
            ],
            options={
                'verbose_name': '部署',
                'verbose_name_plural': '部署',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=5, verbose_name='製品コード')),
                ('product_name', models.CharField(max_length=50, verbose_name='製品名')),
                ('unit_price', models.IntegerField(verbose_name='製品単価')),
            ],
            options={
                'verbose_name': '製品',
                'verbose_name_plural': '製品',
            },
        ),
    ]
