# Generated by Django 5.1.2 on 2025-01-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikkari_app', '0002_department_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='actual_completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='実績完了日'),
        ),
        migrations.AddField(
            model_name='production',
            name='status',
            field=models.CharField(choices=[('pending', '未着手'), ('in_progress', '進行中'), ('completed', '完了')], default='pending', max_length=20, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='production',
            name='manufacture_completion_date',
            field=models.DateTimeField(verbose_name='製造完了予定日'),
        ),
        migrations.AlterField(
            model_name='production',
            name='order_date',
            field=models.DateTimeField(verbose_name='注文日'),
        ),
        migrations.AlterField(
            model_name='production',
            name='product_code',
            field=models.CharField(max_length=5, verbose_name='製品コード'),
        ),
        migrations.AlterField(
            model_name='production',
            name='product_name',
            field=models.CharField(max_length=50, verbose_name='製品名'),
        ),
    ]
